---
- name: Template pg_hba.conf
  template:
    src: pg_hba.conf
    dest: /etc/postgresql/12/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'
  notify:
    - reload postgres
